# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d3f6ddc533093a3c0133275ad1bdbc1a0aa1048def0af55ab2e88520cc5ec7d28d1fd30d018b3d3b6d192591923f68830c0c7c203629b5b763c1d7df5d0b31

test:
  secret_key_base: 2f7b47507f9d6f55d63f2b15438da9b8a410ac03bde17953e5e0c04f592380dd4e1a1940f67f8f66f511a55b70943e8efe9e27122fffa9d20d0913e593b7cf92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
